services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4
    command:
      - start-dev
      - --http-port=3001
    ports:
      - 127.0.0.1:3001:3001
    volumes:
      - keycloakdata:/opt/keycloak/data
    environment:
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "true"
      KC_HOSTNAME: http://keycloak:3001/
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: change_me

#  vmsingle:
#    image: victoriametrics/victoria-metrics:v1.124.0

  vmstorage:
    image: victoriametrics/vmstorage:v1.124.0-cluster

  vminsert:
    image: victoriametrics/vminsert:v1.124.0-cluster
    command:
      - -storageNode=vmstorage:8400

  vmselect:
    image: victoriametrics/vmselect:v1.124.0-cluster
    command:
      - -storageNode=vmstorage:8401
    ports:
      - 8481:8481

#  vmagent:
#    image: victoriametrics/vmagent:v1.124.0
#    volumes:
#      - ./scrape.yaml:/etc/vmagent/config.yaml
#    command:
#      - -promscrape.config=/etc/vmagent/config.yaml
#      - -remoteWrite.url=http://vminsert:8480/insert/multitenant/prometheus/api/v1/write
#      - -remoteWrite.url=http://vmsingle:8428/api/v1/write

  vmauth:
    image: docker.io/victoriametrics/vmauth:heads-jwt-auth-to-vmauth-0-g5c8e020571-dirty-d3a1478e
    ports:
      - 8427:8427
    volumes:
      - ../../../license.txt:/opt/vm-license.key
      - ./vm-auth.yaml:/etc/config.yaml
    command:
      - -licenseFile=/opt/vm-license.key
      - -auth.config=/etc/config.yaml

#  grafana:
#    image: grafana/grafana:12.1.0
#    ports:
#      - 3000:3000
#    environment:
#      GF_SERVER_ROOT_URL: http://grafana:3000
#      GF_AUTH_GENERIC_OAUTH_ENABLED: true
#      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: true
#      GF_AUTH_GENERIC_OAUTH_NAME: keycloak
#      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: grafana
#      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: erBgwExfM7G14OvMbvyf7WJCDUFDOz3S
#      GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_PATH: email
#      GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH: username
#      GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH: full_name
#      GF_AUTH_GENERIC_OAUTH_SCOPES: openid profile email
#      GF_AUTH_GENERIC_OAUTH_USE_REFRESH_TOKEN: true
#      GF_AUTH_GENERIC_OAUTH_AUTH_URL: http://keycloak:3001/realms/master/protocol/openid-connect/auth
#      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: http://keycloak:3001/realms/master/protocol/openid-connect/token
#      GF_AUTH_GENERIC_OAUTH_API_URL: http://keycloak:3001/realms/master/protocol/openid-connect/userinfo
#      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: contains(groups[*], 'grafana-editor') && 'Editor' || 'GrafanaAdmin'
#    volumes:
#      - grafanadata:/var/lib/grafana/

  vmagent:
    image: victoriametrics/vmagent:v1.124.0
    volumes:
      - ./scrape.yaml:/etc/vmagent/config.yaml
    command:
      - -promscrape.config=/etc/vmagent/config.yaml
      - -remoteWrite.url=http://vmauth:8427/insert/api/v1/write
      - -remoteWrite.oauth2.clientID=vmagent
      # The flag is used for demo purposes, in prod consider using -remoteWrite.oauth2.clientSecretFile
      - -remoteWrite.oauth2.clientSecret=5FwqlPWa8WSef9iWZt78vRlCoewNZsKS
      - -remoteWrite.oauth2.tokenUrl=http://keycloak:3001/realms/master/protocol/openid-connect/token
      - -remoteWrite.oauth2.scopes=openid

volumes:
  grafanadata:
  keycloakdata: {}