global:
  scrape_interval: 1s

scrape_configs:
- job_name: vmagent-gh9890
  static_configs:
  - targets:
    - vmagent:8429
- job_name: vminsert-gh9890
  static_configs:
  - targets:
    - vminsert-1:8480
- job_name: vmstorage-gh9890
  static_configs:
  - targets:
    - vmstorage-1:8482
    - vmstorage-2:8482
    - vmstorage-3:8482
